// src/components/games/JogoMemoria.tsx
"use client";

import { useEffect, useState, useCallback } from "react";
import { ALPHABET } from "@/lib/literacy-data";
import { speak, playSound, playWinFanfare } from "@/lib/speech";
import { GameHeader } from "./GameHeader";
import { rewardStars } from "./StarReward";

interface Props {
  onBack: () => void;
  onScore: (score: number, stars: number) => void;
}

type CardKind = "upper" | "lower";

interface Card {
  id: number;
  letter: string;
  kind: CardKind;
  emoji: string;
  color: string;
  flipped: boolean;
  matched: boolean;
}

// Configuração dos níveis progressivos
interface LevelConfig {
  level: number;
  pairs: number;
  cols: number; // colunas no grid
  label: string;
  emoji: string;
  color: string;
}

const LEVELS: LevelConfig[] = [
  { level: 1, pairs: 4, cols: 4, label: "Iniciante", emoji: "🌱", color: "#10b981" },
  { level: 2, pairs: 6, cols: 4, label: "Fácil", emoji: "🌿", color: "#22c55e" },
  { level: 3, pairs: 8, cols: 4, label: "Médio", emoji: "🌳", color: "#f59e0b" },
  { level: 4, pairs: 10, cols: 5, label: "Difícil", emoji: "🔥", color: "#ef4444" },
  { level: 5, pairs: 13, cols: 5, label: "Mestre", emoji: "👑", color: "#8b5cf6" },
];

const MAX_LEVEL = LEVELS.length;

function shuffle<T>(arr: T[]): T[] {
  const a = [...arr];
  for (let i = a.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [a[i], a[j]] = [a[j], a[i]];
  }
  return a;
}

function buildDeck(pairs: number): Card[] {
  const letters = shuffle(ALPHABET).slice(0, pairs);
  const deck: Card[] = [];
  letters.forEach((l, i) => {
    deck.push({
      id: i * 2,
      letter: l.letter,
      kind: "upper" as CardKind,
      emoji: l.emoji,
      color: l.color,
      flipped: false,
      matched: false,
    });
    deck.push({
      id: i * 2 + 1,
      letter: l.lower,
      kind: "lower" as CardKind,
      emoji: l.emoji,
      color: l.color,
      flipped: false,
      matched: false,
    });
  });
  return shuffle(deck);
}

export function JogoMemoria({ onBack, onScore }: Props) {
  const [levelIdx, setLevelIdx] = useState(0); // índice em LEVELS
  const [deck, setDeck] = useState<Card[]>([]);
  const [flipped, setFlipped] = useState<number[]>([]);
  const [moves, setMoves] = useState(0);
  const [matches, setMatches] = useState(0);
  const [score, setScore] = useState(0);
  const [rounds, setRounds] = useState(0);
  const [lock, setLock] = useState(false);
  const [completedLevels, setCompletedLevels] = useState<Set<number>>(new Set());
  const [showLevelUp, setShowLevelUp] = useState(false);

  const currentLevel = LEVELS[levelIdx];
  const pairsForRound = currentLevel.pairs;

  const newGame = useCallback((lvlIdx: number) => {
    setDeck(buildDeck(LEVELS[lvlIdx].pairs));
    setFlipped([]);
    setMoves(0);
    setMatches(0);
    setLock(false);
  }, []);

  useEffect(() => {
    // eslint-disable-next-line react-hooks/set-state-in-effect
    newGame(levelIdx);
  }, [levelIdx, newGame]);

  useEffect(() => {
    speak(`Nível ${currentLevel.level}: ${currentLevel.label}. ${currentLevel.pairs} pares!`, {
      rate: 0.9,
    });
  }, [levelIdx]);

  const changeLevel = (idx: number) => {
    if (idx === levelIdx) return;
    setLevelIdx(idx);
    playSound("click");
  };

  const handleClick = (id: number) => {
    if (lock) return;
    const card = deck.find((c) => c.id === id);
    if (!card || card.flipped || card.matched) return;
    playSound("pop");

    const newDeck = deck.map((c) => (c.id === id ? { ...c, flipped: true } : c));
    const newFlipped = [...flipped, id];
    setDeck(newDeck);
    setFlipped(newFlipped);

    if (newFlipped.length === 2) {
      setLock(true);
      setMoves((m) => m + 1);
      const [a, b] = newFlipped.map((fid) => newDeck.find((c) => c.id === fid)!);
      if (a.emoji === b.emoji && a.kind !== b.kind) {
        // Match!
        setTimeout(() => {
          playSound("correct");
          speak(`${a.letter}`, { rate: 0.8 });
          setDeck((prev) =>
            prev.map((c) => (c.id === a.id || c.id === b.id ? { ...c, matched: true } : c))
          );
          const points = 10 + levelIdx * 3; // mais pontos em níveis maiores
          const newScore = score + points;
          setScore(newScore);
          rewardStars(points);
          const newM = matches + 1;
          setMatches(newM);
          // estrelas baseadas em quantos pares do nível foram feitos
          const stars =
            newM >= pairsForRound ? 3 : newM >= Math.ceil(pairsForRound * 0.6) ? 2 : 1;
          onScore(newScore, stars);

          if (newM >= pairsForRound) {
            // Nível completo!
            playWinFanfare();
            setCompletedLevels((prev) => {
              const copy = new Set(prev);
              copy.add(currentLevel.level);
              return copy;
            });

            // Fala de parabéns
            setTimeout(() => {
              if (levelIdx < MAX_LEVEL - 1) {
                setShowLevelUp(true);
                speak(
                  `Parabéns! Você completou o nível ${currentLevel.level}! Vamos para o nível ${
                    LEVELS[levelIdx + 1].level
                  }!`,
                  { rate: 0.9 }
                );
              } else {
                speak(`Incrível! Você completou todos os níveis! Você é um mestre da memória!`, {
                  rate: 0.9,
                });
              }
            }, 800);

            setRounds((r) => r + 1);

            // Avança para próximo nível após 2.8s (dá tempo do confete + fala)
            setTimeout(() => {
              setShowLevelUp(false);
              if (levelIdx < MAX_LEVEL - 1) {
                setLevelIdx((i) => i + 1);
              } else {
                // Já está no último nível, reinicia no nível 1 para continuar jogando
                setLevelIdx(0);
              }
            }, 2800);
          }
          setFlipped([]);
          setLock(false);
        }, 600);
      } else {
        // No match
        setTimeout(() => {
          playSound("wrong");
          setDeck((prev) =>
            prev.map((c) =>
              c.id === a.id || c.id === b.id ? { ...c, flipped: false } : c
            )
          );
          setFlipped([]);
          setLock(false);
        }, 1100);
      }
    }
  };

  return (
    <div className="min-h-screen bg-gradient-to-b from-violet-50 via-purple-50 to-indigo-50">
      <GameHeader
        title="Jogo da Memória"
        emoji="🧠"
        color="#AA96DA"
        score={score}
        onBack={onBack}
      />

      <main className="mx-auto max-w-3xl px-4 py-6">
        {/* Seleção de níveis */}
        <div className="mb-4">
          <div className="mb-2 text-center text-sm font-bold text-purple-700">
            Escolha seu nível:
          </div>
          <div className="flex flex-wrap justify-center gap-2">
            {LEVELS.map((lvl, idx) => {
              const isActive = idx === levelIdx;
              const isCompleted = completedLevels.has(lvl.level);
              return (
                <button
                  key={lvl.level}
                  onClick={() => changeLevel(idx)}
                  className="flex flex-col items-center rounded-2xl px-3 py-2 text-xs font-bold shadow-md transition hover:scale-105 active:scale-95"
                  style={{
                    background: isActive ? lvl.color : "white",
                    color: isActive ? "white" : lvl.color,
                    border: `3px solid ${lvl.color}`,
                    minWidth: "70px",
                  }}
                >
                  <span className="text-xl">{lvl.emoji}</span>
                  <span>Nível {lvl.level}</span>
                  <span className={isActive ? "opacity-90" : "opacity-70"}>
                    {lvl.pairs} pares
                  </span>
                  {isCompleted && <span className="text-xs">✓</span>}
                </button>
              );
            })}
          </div>
        </div>

        {/* Status do nível atual */}
        <div className="mb-4 flex flex-wrap items-center justify-center gap-3 text-sm font-bold text-purple-700">
          <span
            className="rounded-full px-4 py-1.5 text-white shadow"
            style={{ background: currentLevel.color }}
          >
            {currentLevel.emoji} {currentLevel.label}
          </span>
          <span className="rounded-full bg-white px-4 py-1.5 shadow">
            Pares: <span className="text-purple-900">{matches}</span> / {pairsForRound}
          </span>
          <span className="rounded-full bg-white px-4 py-1.5 shadow">
            Jogadas: <span className="text-purple-900">{moves}</span>
          </span>
          <button
            onClick={() => newGame(levelIdx)}
            className="rounded-full bg-purple-100 px-4 py-1.5 font-bold text-purple-700 hover:bg-purple-200"
          >
            ↻ Recomeçar
          </button>
        </div>

        <div className="mb-3 text-center text-sm font-bold text-purple-700">
          Encontre os pares: <span className="text-purple-900">MAIÚSCULA</span> ↔{" "}
          <span className="text-purple-900">minúscula</span>
        </div>

        {/* Tabuleiro - grid dinâmico */}
        <div
          className="mx-auto grid gap-2 sm:gap-3"
          style={{
            gridTemplateColumns: `repeat(${currentLevel.cols}, minmax(0, 1fr))`,
            maxWidth: currentLevel.cols >= 5 ? "560px" : "480px",
          }}
        >
          {deck.map((card) => {
            const showFront = card.flipped || card.matched;
            return (
              <button
                key={card.id}
                onClick={() => handleClick(card.id)}
                disabled={card.matched}
                className="relative aspect-square rounded-xl shadow-md transition-transform duration-200 hover:scale-105"
                style={{
                  background: showFront ? card.color : "white",
                  border: `3px solid ${showFront ? card.color : "#c4b5fd"}`,
                  opacity: card.matched ? 0.55 : 1,
                }}
              >
                {showFront ? (
                  <div className="flex h-full flex-col items-center justify-center gap-0.5">
                    <div
                      className="font-black text-white"
                      style={{
                        fontSize:
                          currentLevel.cols >= 5 ? "1.4rem" : "1.75rem",
                        textShadow: "0 2px 4px rgba(0,0,0,0.3)",
                      }}
                    >
                      {card.letter}
                    </div>
                    <div
                      style={{
                        fontSize: currentLevel.cols >= 5 ? "0.95rem" : "1.25rem",
                      }}
                    >
                      {card.emoji}
                    </div>
                  </div>
                ) : (
                  <div className="flex h-full items-center justify-center text-purple-300">
                    <span style={{ fontSize: currentLevel.cols >= 5 ? "1.25rem" : "1.75rem" }}>
                      ❓
                    </span>
                  </div>
                )}
              </button>
            );
          })}
        </div>

        <div className="mt-5 text-center text-sm text-purple-600">
          Rodadas completas: {rounds} · Níveis desbloqueados: {completedLevels.size} / {MAX_LEVEL}
        </div>

        {/* Modal de Level Up */}
        {showLevelUp && (
          <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 p-4 backdrop-blur-sm">
            <div
              className="rounded-3xl bg-white p-8 text-center shadow-2xl"
              style={{ border: `5px solid ${LEVELS[levelIdx + 1]?.color ?? currentLevel.color}` }}
            >
              <div className="text-6xl animate-bounce">🎉</div>
              <h2 className="mt-3 text-2xl font-black text-purple-700">Nível Completo!</h2>
              <p className="mt-2 text-base font-bold text-purple-600">
                Você terminou o nível {currentLevel.level}!
              </p>
              <div className="mt-4 flex items-center justify-center gap-2">
                <span className="text-3xl">{currentLevel.emoji}</span>
                <span className="text-2xl">→</span>
                <span className="text-3xl">{LEVELS[levelIdx + 1]?.emoji ?? "👑"}</span>
              </div>
              <p className="mt-3 text-sm font-bold text-purple-500">
                Próximo: Nível {LEVELS[levelIdx + 1]?.level ?? "Max"} ·{" "}
                {LEVELS[levelIdx + 1]?.label ?? "Mestre"}
              </p>
            </div>
          </div>
        )}
      </main>
    </div>
  );
}

// src/components/games/JogoMemoria.vue
<script setup lang="ts">
import { ref, computed, watch, onMounted, onUnmounted } from 'vue'
import { ALPHABET } from '@/lib/literacy-data'
import { speak, playSound, playWinFanfare } from '@/lib/speech'
import { rewardStars } from '@/components/StarReward.vue'
import GameHeader from '@/components/games/GameHeader.vue'

const emit = defineEmits<{
  back: []
  score: [score: number, stars: number]
}>()

const LEVELS = [
  { level: 1, pairs: 4, cols: 4, label: 'Iniciante' },
  { level: 2, pairs: 6, cols: 4, label: 'Fácil' },
  { level: 3, pairs: 8, cols: 4, label: 'Médio' },
  { level: 4, pairs: 10, cols: 5, label: 'Difícil' },
  { level: 5, pairs: 13, cols: 5, label: 'Mestre' },
]

interface Card {
  id: number
  letter: string
  kind: 'upper' | 'lower'
  emoji: string
  color: string
  flipped: boolean
  matched: boolean
}

function shuffle<T>(arr: T[]): T[] {
  const a = [...arr]
  for (let i = a.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1))
    ;[a[i], a[j]] = [a[j], a[i]]
  }
  return a
}

const levelIdx = ref(0)
const deck = ref<Card[]>([])
const flipped = ref<number[]>([])
const moves = ref(0)
const matches = ref(0)
const score = ref(0)
const rounds = ref(0)
const lock = ref(false)
const completedLevels = ref(new Set<number>())
const showLevelUp = ref(false)

const currentLevel = computed(() => LEVELS[levelIdx.value])
const maxPairs = computed(() => currentLevel.value.pairs)
const unlockedLevels = computed(() => {
  let count = 1
  for (let i = 1; i < LEVELS.length; i++) {
    if (completedLevels.value.has(i - 1)) count++
    else break
  }
  return count
})

function computeStars(): number {
  if (rounds.value >= 3) return 3
  if (rounds.value >= 1) return 2
  return 1
}

function buildDeck(pairs: number) {
  const shuffledLetters = shuffle([...ALPHABET]).slice(0, pairs)
  const cardPairs: Card[] = []
  let id = 0
  for (const l of shuffledLetters) {
    cardPairs.push({
      id: id++,
      letter: l.letter,
      kind: 'upper',
      emoji: l.emoji,
      color: l.color,
      flipped: false,
      matched: false,
    })
    cardPairs.push({
      id: id++,
      letter: l.lower,
      kind: 'lower',
      emoji: l.emoji,
      color: l.color,
      flipped: false,
      matched: false,
    })
  }
  return shuffle(cardPairs)
}

function newGame() {
  deck.value = buildDeck(currentLevel.value.pairs)
  flipped.value = []
  lock.value = false
  matches.value = 0
  moves.value = 0
  showLevelUp.value = false
}

function handleClick(cardId: number) {
  if (lock.value) return
  const card = deck.value.find((c) => c.id === cardId)
  if (!card) return
  if (card.flipped || card.matched) return

  playSound('pop')
  card.flipped = true
  flipped.value = [...flipped.value, cardId]

  if (flipped.value.length === 2) {
    moves.value++
    lock.value = true
    const [id1, id2] = flipped.value
    const c1 = deck.value.find((c) => c.id === id1)!
    const c2 = deck.value.find((c) => c.id === id2)!

    // Match: same emoji, different kind (upper vs lower)
    if (c1.emoji === c2.emoji && c1.kind !== c2.kind) {
      setTimeout(() => {
        c1.matched = true
        c2.matched = true
        matches.value++
        const points = 10 + levelIdx.value * 3
        score.value += points
        playSound('correct')
        rewardStars(points)
        speak(c1.letter.toUpperCase())
        flipped.value = []
        lock.value = false

        if (matches.value === maxPairs.value) {
          handleLevelComplete()
        }
      }, 400)
    } else {
      setTimeout(() => {
        c1.flipped = false
        c2.flipped = false
        flipped.value = []
        lock.value = false
      }, 1100)
    }
  }
}

function handleLevelComplete() {
  playWinFanfare()
  completedLevels.value = new Set([...completedLevels.value, levelIdx.value])
  rounds.value++
  showLevelUp.value = true
  emit('score', score.value, computeStars())

  setTimeout(() => {
    showLevelUp.value = false
    const nextLvl = (levelIdx.value + 1) % LEVELS.length
    levelIdx.value = nextLvl
  }, 2800)
}

function selectLevel(lvlIdx: number) {
  if (lvlIdx > unlockedLevels.value - 1) return
  playSound('click')
  levelIdx.value = lvlIdx
}

watch(levelIdx, () => {
  newGame()
  speak(`Nível ${LEVELS[levelIdx.value].label}. Encontre os pares!`, { rate: 0.85 })
})

onMounted(() => {
  newGame()
})

onUnmounted(() => {
  if (score.value > 0) {
    emit('score', score.value, computeStars())
  }
})
</script>

<template>
  <div class="min-h-screen bg-gradient-to-b from-violet-50 via-purple-50 to-indigo-50">
    <GameHeader
      title="Jogo da Memória"
      emoji="🧠"
      color="#AA96DA"
      :score="score"
      @back="emit('back')"
    />

    <main class="mx-auto max-w-2xl px-4 py-5 sm:py-7">
      <!-- Level selector -->
      <div class="mb-4 flex flex-wrap justify-center gap-2">
        <button
          v-for="(lvl, i) in LEVELS"
          :key="lvl.level"
          @click="selectLevel(i)"
          :disabled="i > unlockedLevels - 1"
          class="rounded-full px-4 py-2 text-sm font-bold shadow-md transition hover:scale-105 active:scale-95 disabled:opacity-30"
          :style="{
            background: i === levelIdx ? '#7c3aed' : 'white',
            color: i === levelIdx ? 'white' : '#7c3aed',
            border: '2px solid #7c3aed',
          }"
        >
          {{ lvl.level }}. {{ lvl.label }}
          <span v-if="completedLevels.has(i)"> ✓</span>
        </button>
      </div>

      <!-- Status bar -->
      <div class="mb-3 flex items-center justify-center gap-4 text-sm font-bold text-violet-700">
        <span class="inline-block rounded-full bg-white px-4 py-1.5 shadow">
          Pares: {{ matches }} / {{ maxPairs }}
        </span>
        <span class="inline-block rounded-full bg-white px-4 py-1.5 shadow">
          Jogadas: {{ moves }}
        </span>
      </div>

      <!-- Hint -->
      <p class="mb-4 text-center text-xs italic text-violet-400">
        Encontre os pares: MAIÚSCULA ↔ minúscula
      </p>

      <!-- Card grid -->
      <div
        class="mx-auto grid max-w-md gap-2"
        :style="{ gridTemplateColumns: `repeat(${currentLevel.cols}, 1fr)` }"
      >
        <button
          v-for="card in deck"
          :key="card.id"
          @click="handleClick(card.id)"
          class="aspect-square rounded-xl text-center shadow-md transition-all duration-300 active:scale-95"
          :class="{
            'opacity-50 pointer-events-none': card.matched,
          }"
          :style="
            card.flipped || card.matched
              ? { background: card.color, color: 'white' }
              : { background: '#7c3aed', color: 'white' }
          "
        >
          <template v-if="card.flipped || card.matched">
            <div class="flex flex-col items-center justify-center h-full">
              <span class="text-xs leading-none mb-0.5 sm:text-sm">{{ card.emoji }}</span>
              <span class="text-xl font-black leading-none sm:text-3xl">{{ card.letter }}</span>
            </div>
          </template>
          <template v-else>
            <div class="flex h-full items-center justify-center">
              <span class="text-2xl sm:text-3xl">❓</span>
            </div>
          </template>
        </button>
      </div>

      <!-- Footer stats -->
      <div class="mt-5 text-center text-sm font-bold text-violet-600">
        Rodadas completas: {{ rounds }} · Níveis desbloqueados: {{ unlockedLevels }} / 5
      </div>
    </main>

    <!-- Level-up modal overlay -->
    <Transition name="fade">
      <div
        v-if="showLevelUp"
        class="fixed inset-0 z-30 flex items-center justify-center bg-black/40"
        @click.stop
      >
        <div class="rounded-3xl bg-white px-10 py-8 text-center shadow-2xl animate-bounce">
          <p class="text-5xl mb-2">🎉</p>
          <p class="text-2xl font-black text-gray-800">Nível Completo!</p>
          <p class="mt-1 text-sm text-gray-500">
            Próximo: {{ LEVELS[(levelIdx + 1) % LEVELS.length].label }}
          </p>
        </div>
      </div>
    </Transition>
  </div>
</template>

<style scoped>
.fade-enter-active,
.fade-leave-active {
  transition: opacity 0.3s ease;
}
.fade-enter-from,
.fade-leave-to {
  opacity: 0;
}
</style>
