// src/components/games/Silabas.vue
<script setup lang="ts">
import { ref, computed, watch, onMounted, onUnmounted } from 'vue'
import { SYLLABLE_WORDS, type SyllableWord } from '@/lib/literacy-data'
import { speak, playSound, playWinFanfare } from '@/lib/speech'
import { rewardStars } from '@/components/StarReward.vue'
import GameHeader from '@/components/games/GameHeader.vue'

const emit = defineEmits<{
  back: []
  score: [score: number, stars: number]
}>()

function shuffle<T>(arr: T[]): T[] {
  const a = [...arr]
  for (let i = a.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1))
    ;[a[i], a[j]] = [a[j], a[i]]
  }
  return a
}

const round = ref<SyllableWord | null>(null)
const picked = ref<number | null>(null)
const score = ref(0)
const solved = ref(0)
const attempts = ref(0)
const clapCount = ref(0)
const clapping = ref(false)
let syllableTimers: ReturnType<typeof setTimeout>[] = []

const options = computed(() => {
  if (!round.value) return []
  const correct = round.value.syllables
  const counts = [...new Set(SYLLABLE_WORDS.map((w) => w.syllables))].sort((a, b) => a - b)
  const available = counts.filter((n) => n !== correct)
  const wrong = shuffle(available).slice(0, 3)
  return shuffle([correct, ...wrong])
})

function computeStars(): number {
  if (solved.value >= 8) return 3
  if (solved.value >= 4) return 2
  return 1
}

function clearSyllableTimers() {
  syllableTimers.forEach((t) => clearTimeout(t))
  syllableTimers = []
}

function buildRound() {
  clearSyllableTimers()
  picked.value = null
  clapCount.value = 0
  clapping.value = false

  const word = SYLLABLE_WORDS[Math.floor(Math.random() * SYLLABLE_WORDS.length)]
  round.value = word
}

function showClaps() {
  if (!round.value || clapping.value) return
  clapping.value = true
  clearSyllableTimers()

  const breakdown = round.value.syllableBreakdown
  breakdown.forEach((syllable, i) => {
    const t1 = setTimeout(() => {
      clapCount.value = i + 1
      playSound('pop')
      speak(syllable, { rate: 0.7 })
    }, i * 700)
    syllableTimers.push(t1)
  })

  const tEnd = setTimeout(() => {
    clapCount.value = 0
    clapping.value = false
  }, breakdown.length * 700 + 500)
  syllableTimers.push(tEnd)
}

function handlePick(n: number) {
  if (!round.value || picked.value !== null) return

  if (n === round.value.syllables) {
    // Correct
    picked.value = n
    playSound('correct')
    score.value += 10
    rewardStars(10)
    solved.value++

    speak(`${round.value.syllables} sílabas! Muito bem!`)

    if (solved.value % 5 === 0) {
      playWinFanfare()
    }

    emit('score', score.value, computeStars())

    setTimeout(() => {
      buildRound()
    }, 1800)
  } else {
    // Wrong
    picked.value = n
    attempts.value++
    playSound('wrong')
    speak('Quase!')

    setTimeout(() => {
      picked.value = null
    }, 1200)
  }
}

watch(round, () => {
  if (round.value) {
    setTimeout(() => speak(`Quantas sílabas tem ${round.value!.word}?`, { rate: 0.85 }), 300)
  }
})

onMounted(() => {
  buildRound()
})

onUnmounted(() => {
  clearSyllableTimers()
  if (score.value > 0) {
    emit('score', score.value, computeStars())
  }
})
</script>

<template>
  <div class="min-h-screen bg-gradient-to-b from-yellow-50 via-amber-50 to-orange-50">
    <GameHeader
      title="Sílabas"
      emoji="👏"
      color="#FFD93D"
      :score="score"
      @back="emit('back')"
    />

    <main class="mx-auto max-w-2xl px-4 py-6 sm:py-8">
      <div v-if="round" class="flex flex-col items-center gap-5">
        <!-- Bouncing emoji -->
        <div
          class="text-7xl sm:text-8xl select-none animate-bounce drop-shadow-md"
        >
          {{ round.emoji }}
        </div>

        <!-- Word button -->
        <div
          class="rounded-3xl bg-gradient-to-br from-amber-400 to-orange-400 px-8 py-4 text-3xl font-black text-white shadow-xl"
        >
          {{ round.word }}
        </div>

        <!-- Ouvir as sílabas button -->
        <button
          @click="showClaps"
          :disabled="clapping"
          class="rounded-full bg-amber-500 px-6 py-3 text-lg font-bold text-white shadow-lg transition hover:bg-amber-600 active:scale-95 disabled:opacity-50"
        >
          👏 Ouvir as sílabas
        </button>

        <!-- Clap animation row (👏 + syllable labels) -->
        <div class="flex justify-center gap-2 flex-wrap">
          <span
            v-for="(syllable, i) in round.syllableBreakdown"
            :key="i"
            class="inline-flex items-center gap-1 rounded-xl px-3 py-1.5 text-lg font-bold transition-all duration-200"
            :style="
              clapCount > i
                ? 'background: #fbbf24; color: #78350f; transform: scale(1.2); box-shadow: 0 4px 14px rgba(251,191,36,0.6)'
                : 'background: #f1f5f9; color: #94a3b8'
            "
          >
            👏 {{ syllable }}
          </span>
        </div>

        <!-- 4 option buttons (1-4 sílabas) -->
        <div class="flex flex-wrap justify-center gap-3 mt-2">
          <button
            v-for="n in options"
            :key="n"
            @click="handlePick(n)"
            class="w-24 h-24 rounded-2xl flex flex-col items-center justify-center text-center font-black shadow-lg transition-all duration-150 active:scale-90 hover:scale-105"
            :style="{
              background: picked === n
                ? n === round.syllables
                  ? '#16a34a'
                  : '#ef4444'
                : 'white',
              color: picked === n ? 'white' : '#1e293b',
              border: picked === n
                ? '3px solid ' + (n === round.syllables ? '#15803d' : '#b91c1c')
                : '3px solid #e2e8f0',
              boxShadow: picked === n && n === round.syllables
                ? '0 0 20px rgba(22,163,74,0.5)'
                : 'none',
            }"
          >
            <span class="text-4xl">{{ n }}</span>
            <span class="text-xs mt-0.5">sílaba{{ n > 1 ? 's' : '' }}</span>
          </button>
        </div>
      </div>

      <!-- Stats -->
      <div class="mt-6 flex gap-6 text-sm font-bold text-amber-700 justify-center">
        <span>Acertos: {{ solved }}</span>
        <span>Tentativas: {{ attempts }}</span>
      </div>
    </main>
  </div>
</template>

// src/components/games/Silabas.tsx
"use client";

import { useEffect, useState, useCallback } from "react";
import { SYLLABLE_WORDS, type SyllableWord } from "@/lib/literacy-data";
import { speak, playSound, playWinFanfare } from "@/lib/speech";
import { GameHeader } from "./GameHeader";
import { rewardStars } from "./StarReward";

interface Props {
  onBack: () => void;
  onScore: (score: number, stars: number) => void;
}

function shuffle<T>(arr: T[]): T[] {
  const a = [...arr];
  for (let i = a.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [a[i], a[j]] = [a[j], a[i]];
  }
  return a;
}

function buildRound(): SyllableWord {
  return SYLLABLE_WORDS[Math.floor(Math.random() * SYLLABLE_WORDS.length)];
}

export function Silabas({ onBack, onScore }: Props) {
  const [round, setRound] = useState<SyllableWord | null>(null);
  const [picked, setPicked] = useState<number | null>(null);
  const [score, setScore] = useState(0);
  const [solved, setSolved] = useState(0);
  const [attempts, setAttempts] = useState(0);
  const [clapCount, setClapCount] = useState(0);
  const [clapping, setClapping] = useState(false);

  const next = useCallback(() => {
    setRound(buildRound());
    setPicked(null);
    setClapCount(0);
  }, []);

  useEffect(() => {
    // eslint-disable-next-line react-hooks/set-state-in-effect
    next();
  }, [next]);

  useEffect(() => {
    if (!round) return;
    const t = setTimeout(() => speak(`Quantas sílabas tem ${round.word}?`, { rate: 0.85 }), 300);
    return () => clearTimeout(t);
  }, [round]);

  // Reproduz as palmas rítmicas mostrando as sílabas
  const showClaps = () => {
    if (!round || clapping) return;
    setClapping(true);
    setClapCount(0);
    playSound("click");
    round.syllableBreakdown.forEach((syl, i) => {
      setTimeout(() => {
        setClapCount(i + 1);
        playSound("pop");
        speak(syl, { rate: 0.7 });
      }, i * 700);
    });
    setTimeout(() => {
      setClapping(false);
    }, round.syllableBreakdown.length * 700 + 200);
  };

  const handlePick = (n: number) => {
    if (picked !== null || !round) return;
    setPicked(n);
    if (n === round.syllables) {
      playSound("correct");
      const points = 10;
      const newScore = score + points;
      setScore(newScore);
      rewardStars(points);
      const newSolved = solved + 1;
      setSolved(newSolved);
      onScore(newScore, newSolved >= 8 ? 3 : newSolved >= 4 ? 2 : 1);
      speak(`${round.syllables} sílabas! Muito bem!`, { rate: 0.85 });
      if (newSolved >= 5 && newSolved % 5 === 0) playWinFanfare();
      setTimeout(next, 1800);
    } else {
      playSound("wrong");
      setAttempts((a) => a + 1);
      speak(`Quase! Ouça de novo.`, { rate: 0.85 });
      setTimeout(() => setPicked(null), 1200);
    }
  };

  if (!round) return null;

  const options = [1, 2, 3, 4].filter((n) => n <= 4);

  return (
    <div className="min-h-screen bg-gradient-to-b from-yellow-50 via-amber-50 to-orange-50">
      <GameHeader
        title="Sílabas"
        emoji="👏"
        color="#FFD93D"
        score={score}
        onBack={onBack}
      />
      <main className="mx-auto max-w-2xl px-4 py-6">
        <div className="mb-3 text-center text-base font-bold text-amber-800">
          Quantas sílabas tem essa palavra?
        </div>

        {/* Palavra */}
        <div className="flex flex-col items-center gap-4">
          <div className="text-7xl sm:text-8xl drop-shadow-md select-none animate-[bounce_2s_ease-in-out_infinite]">
            {round.emoji}
          </div>
          <button
            onClick={() => speak(round.word, { rate: 0.75 })}
            className="rounded-2xl bg-white px-6 py-3 text-3xl sm:text-4xl font-black text-amber-700 shadow-lg"
            style={{ border: "3px solid #f59e0b" }}
          >
            {round.word}
          </button>

          <button
            onClick={showClaps}
            disabled={clapping}
            className="rounded-full bg-amber-500 px-5 py-2.5 text-sm font-bold text-white shadow-md transition hover:scale-105 active:scale-95 disabled:opacity-60"
          >
            👏 Ouvir as sílabas
          </button>

          {/* Animação de palmas */}
          <div className="flex h-20 items-center justify-center gap-3">
            {round.syllableBreakdown.map((syl, i) => (
              <div
                key={i}
                className="flex flex-col items-center gap-1"
              >
                <div
                  className="text-4xl transition-transform"
                  style={{
                    transform:
                      clapCount > i ? "scale(1.3)" : "scale(1)",
                    filter: clapCount > i ? "drop-shadow(0 0 8px #f59e0b)" : "none",
                  }}
                >
                  👏
                </div>
                <div
                  className="rounded-md px-2 py-0.5 text-sm font-bold"
                  style={{
                    background: clapCount > i ? "#f59e0b" : "#fef3c7",
                    color: clapCount > i ? "white" : "#92400e",
                  }}
                >
                  {syl}
                </div>
              </div>
            ))}
          </div>
        </div>

        {/* Opções */}
        <div className="mt-6 text-center text-sm font-bold text-amber-700">
          Escolha quantas sílabas:
        </div>
        <div className="mt-3 flex flex-wrap justify-center gap-4">
          {options.map((n) => {
            const isPicked = picked === n;
            const isCorrect = n === round.syllables;
            return (
              <button
                key={n}
                onClick={() => handlePick(n)}
                disabled={picked !== null}
                className="flex h-24 w-24 flex-col items-center justify-center rounded-2xl shadow-lg transition hover:scale-105 active:scale-95 disabled:cursor-not-allowed"
                style={{
                  background: picked
                    ? isCorrect
                      ? "#10b981"
                      : isPicked
                      ? "#ef4444"
                      : "#e5e7eb"
                    : "white",
                  color: picked
                    ? isCorrect || isPicked
                      ? "white"
                      : "#9ca3af"
                    : "#92400e",
                  border: `4px solid ${
                    picked
                      ? isCorrect
                        ? "#047857"
                        : isPicked
                        ? "#b91c1c"
                        : "#d1d5db"
                      : "#fbbf24"
                  }`,
                }}
              >
                <div className="text-5xl font-black">{n}</div>
                <div className="text-xs font-bold opacity-80">sílabas</div>
              </button>
            );
          })}
        </div>

        <div className="mt-6 flex justify-center gap-3 text-sm font-bold text-amber-700">
          <span className="rounded-full bg-white px-4 py-1.5 shadow">
            Acertos: <span className="text-amber-900">{solved}</span>
          </span>
          <span className="rounded-full bg-white px-4 py-1.5 shadow">
            Erros: <span className="text-amber-900">{attempts}</span>
          </span>
        </div>
      </main>
    </div>
  );
}
