// src/components/games/StarReward.tsx
"use client";

import { useEffect, useState } from "react";

interface FloatingStar {
  id: number;
  amount: number;
}

// Mostra "+N ⭐" subindo na tela quando o jogador pontua
export function StarReward() {
  const [stars, setStars] = useState<FloatingStar[]>([]);

  useEffect(() => {
    const handler = (e: Event) => {
      const detail = (e as CustomEvent<number>).detail;
      const id = Date.now() + Math.random();
      setStars((prev) => [...prev, { id, amount: detail }]);
      setTimeout(() => {
        setStars((prev) => prev.filter((s) => s.id !== id));
      }, 1100);
    };
    window.addEventListener("abc:star", handler as EventListener);
    return () => window.removeEventListener("abc:star", handler as EventListener);
  }, []);

  return (
    <div className="pointer-events-none fixed inset-0 z-[90] flex items-start justify-center">
      {stars.map((s) => (
        <div
          key={s.id}
          className="absolute top-1/3 text-4xl sm:text-5xl font-extrabold"
          style={{
            color: "#FFD93D",
            textShadow: "0 4px 0 #FFA500, 0 8px 12px rgba(0,0,0,0.3)",
            animation: "starFloat 1.1s ease-out forwards",
          }}
        >
          +{s.amount} ⭐
        </div>
      ))}
      <style jsx>{`
        @keyframes starFloat {
          0% {
            transform: translateY(0) scale(0.4);
            opacity: 0;
          }
          30% {
            transform: translateY(-30px) scale(1.2);
            opacity: 1;
          }
          100% {
            transform: translateY(-150px) scale(0.9);
            opacity: 0;
          }
        }
      `}</style>
    </div>
  );
}

// Dispara o evento global
export function rewardStars(amount: number) {
  if (typeof window === "undefined") return;
  window.dispatchEvent(new CustomEvent("abc:star", { detail: amount }));
}

// src/components/StarReward.vue
<script lang="ts">
export function rewardStars(amount: number) {
  if (typeof window === 'undefined') return
  window.dispatchEvent(new CustomEvent('abc:star', { detail: amount }))
}
</script>

<script setup lang="ts">
import { ref, onMounted, onUnmounted } from 'vue'

interface FloatingStar {
  id: number
  amount: number
}

const stars = ref<FloatingStar[]>([])

function handler(e: Event) {
  const detail = (e as CustomEvent<number>).detail
  const id = Date.now() + Math.random()
  stars.value = [...stars.value, { id, amount: detail }]
  setTimeout(() => {
    stars.value = stars.value.filter((s) => s.id !== id)
  }, 1100)
}

onMounted(() => {
  window.addEventListener('abc:star', handler as EventListener)
})

onUnmounted(() => {
  window.removeEventListener('abc:star', handler as EventListener)
})
</script>

<template>
  <div class="pointer-events-none fixed inset-0 z-[90] flex items-start justify-center">
    <div
      v-for="s in stars"
      :key="s.id"
      class="absolute top-1/3 text-4xl sm:text-5xl font-extrabold"
      style="color: #FFD93D; text-shadow: 0 4px 0 #FFA500, 0 8px 12px rgba(0,0,0,0.3); animation: starFloat 1.1s ease-out forwards;"
    >
      +{{ s.amount }} ⭐
    </div>
  </div>
</template>
